services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:5000"
    environment:
      FLASK_ENV: development
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_NAME: my_database
      DB_USER: my_user
      DB_PASSWORD: my_password
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DB: my_mongo_database
      API_SECRET_KEY: vqfTeqBAUcxQuAkTREjruoDijTmXFhUI
      API_PUBLIC_KEY: MmfcvMQxMCjgXjBrWqKt
      APP_NAME: UniversityProjectVinylStore
    depends_on:
      - mariadb
      - mongodb

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_DATABASE: my_database
      MARIADB_USER: my_user
      MARIADB_PASSWORD: my_password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: my_mongo_database
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mariadb_data:
  mongo_data:
